import { supabase, getUserId, isSupabaseAvailable } from './supabaseClient';
import type { Database } from '../types/supabase';
import type { IskraMetrics, IskraPhase, MemoryNode, SIFTBlock } from '../types';

// We use the generated types for DB interactions
type VoicePreferences = Record<string, number>;

interface Message {
  role: 'user' | 'model';
  text: string;
  deltaSignature?: string;
  voice?: { name: string };
}


const safeStorage = {
  getItem: (key: string) => {
    if (typeof window !== 'undefined') return localStorage.getItem(key);
    return null;
  },
  setItem: (key: string, value: string) => {
    if (typeof window !== 'undefined') localStorage.setItem(key, value);
  },
};

// =============================================================================
// USER & ONBOARDING
// =============================================================================

export async function getOrCreateUser(name?: string): Promise<{ id: string; name: string; isNew: boolean }> {
  const userId = await getUserId();

  // Try to get existing
  const { data: existingUser, error: fetchError } = await supabase
    .from('users')
    .select('*')
    .eq('id', userId)
    .single();

  if (existingUser && !fetchError) {
    return {
      id: existingUser.id,
      name: existingUser.name || 'Anonymous',
      isNew: false
    };
  }

  // Create new
  const { data: newUser, error: insertError } = await supabase
    .from('users')
    .insert({
      id: userId,
      name: name || 'Traveler',
      onboarding_complete: false,
      tutorial_complete: false,
      settings: {},
    })
    .select()
    .single();

  if (insertError) {
    console.error('Failed to create user:', insertError);
    // Return dummy if DB fails
    return { id: userId, name: name || 'Traveler', isNew: true };
  }

  return {
    id: newUser.id,
    name: newUser.name || 'Traveler',
    isNew: true
  };
}

export async function updateUser(updates: Database['public']['Tables']['users']['Update']): Promise<void> {
  const userId = await getUserId();
  const { error } = await supabase
    .from('users')
    .update(updates)
    .eq('id', userId);

  if (error) console.error('Failed to update user:', error);
}

export async function completeOnboarding(): Promise<void> {
  await updateUser({ onboarding_complete: true });
}

export async function completeTutorial(): Promise<void> {
  await updateUser({ tutorial_complete: true });
}

export async function isOnboardingComplete(): Promise<boolean> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('users')
    .select('onboarding_complete')
    .eq('id', userId)
    .single();

  if (error || !data) return false;
  return data.onboarding_complete ?? false;
}

// =============================================================================
// TASKS & HABITS
// =============================================================================

export async function getTasks(): Promise<Database['public']['Tables']['tasks']['Row'][]> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('tasks')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Failed to fetch tasks:', error);
    return [];
  }
  return data || [];
}

export async function saveTasks(tasks: Database['public']['Tables']['tasks']['Insert'][]): Promise<void> {
  const userId = await getUserId();
  if (tasks.length === 0) {
    // Nothing to save — clear all tasks atomically
    const { error } = await supabase.from('tasks').delete().eq('user_id', userId);
    if (error) console.error('Failed to clear tasks:', error);
    return;
  }

  // Atomic upsert — no data loss if network drops after partial write.
  // Requires tasks.id to be stable across saves (generated by storageService).
  const rows = tasks.map(t => ({ ...t, user_id: userId }));
  const { error } = await supabase
    .from('tasks')
    .upsert(rows, { onConflict: 'id', ignoreDuplicates: false });

  if (error) console.error('Failed to save tasks:', error);
}

export async function addTask(task: Database['public']['Tables']['tasks']['Insert']): Promise<Database['public']['Tables']['tasks']['Row'] | null> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('tasks')
    .insert({ ...task, user_id: userId })
    .select()
    .single();

  if (error) {
    console.error('Failed to add task:', error);
    return null;
  }
  return data;
}

export async function updateTask(id: string, updates: Database['public']['Tables']['tasks']['Update']): Promise<void> {
  const { error } = await supabase
    .from('tasks')
    .update(updates)
    .eq('id', id);

  if (error) console.error('Failed to update task:', error);
}

export async function deleteTask(id: string): Promise<void> {
  const { error } = await supabase.from('tasks').delete().eq('id', id);
  if (error) console.error('Failed to delete task:', error);
}

export async function getHabits(): Promise<Database['public']['Tables']['habits']['Row'][]> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('habits')
    .select('*')
    .eq('user_id', userId);

  if (error) {
    console.error('Failed to get habits:', error);
    return [];
  }
  return data || [];
}

export async function saveHabits(habits: Database['public']['Tables']['habits']['Insert'][]): Promise<void> {
  const userId = await getUserId();
  if (habits.length === 0) {
    const { error } = await supabase.from('habits').delete().eq('user_id', userId);
    if (error) console.error('Failed to clear habits:', error);
    return;
  }

  // Atomic upsert — prevents data loss on partial write failure.
  const rows = habits.map(h => ({ ...h, user_id: userId }));
  const { error } = await supabase
    .from('habits')
    .upsert(rows, { onConflict: 'id', ignoreDuplicates: false });

  if (error) console.error('Failed to save habits:', error);
}

// =============================================================================
// JOURNAL
// =============================================================================

export async function getJournalEntries(): Promise<Database['public']['Tables']['journal_entries']['Row'][]> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('journal_entries')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Failed to get journal:', error);
    return [];
  }
  return data || [];
}

export async function addJournalEntry(entry: Database['public']['Tables']['journal_entries']['Insert']): Promise<void> {
  const userId = await getUserId();
  const { error } = await supabase
    .from('journal_entries')
    .insert({ ...entry, user_id: userId });

  if (error) console.error('Failed to add journal entry:', error);
}

// =============================================================================
// METRICS SNAPSHOTS
// =============================================================================

export async function saveMetricsSnapshot(metrics: IskraMetrics, phase: string): Promise<void> {
  const userId = await getUserId();
  const snapshot = { metrics, phase, timestamp: new Date().toISOString() };
  
  // Save to local storage as fallback/cache
  safeStorage.setItem(`metrics_latest_${userId}`, JSON.stringify(snapshot));

  const { error } = await supabase.from('metrics_snapshots').insert({
    user_id: userId,
    rhythm: metrics.rhythm,
    trust: metrics.trust,
    clarity: metrics.clarity,
    pain: metrics.pain,
    drift: metrics.drift,
    chaos: metrics.chaos,
    echo: metrics.echo,
    silence_mass: metrics.silence_mass,
    mirror_sync: metrics.mirror_sync,
    interrupt: metrics.interrupt,
    ctx_switch: metrics.ctxSwitch,
    phase,
  });

  if (error) console.error('Failed to save metrics snapshot:', error);
}

export async function getLatestMetrics(): Promise<{ metrics: IskraMetrics; phase: IskraPhase } | null> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('metrics_snapshots')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (error || !data) {
    // Fallback to localStorage
    const cached = safeStorage.getItem(`metrics_latest_${userId}`);
    if (cached) {
      try {
        const snapshot = JSON.parse(cached) as { metrics: IskraMetrics; phase: IskraPhase };
        return snapshot;
      } catch {
        return null;
      }
    }
    return null;
  }

  const result = {
    metrics: {
      rhythm: data.rhythm ?? 0,
      trust: data.trust ?? 0,
      clarity: data.clarity ?? 0,
      pain: data.pain ?? 0,
      drift: data.drift ?? 0,
      chaos: data.chaos ?? 0,
      echo: data.echo ?? 0,
      silence_mass: data.silence_mass ?? 0,
      mirror_sync: data.mirror_sync ?? 0,
      interrupt: data.interrupt ?? 0,
      ctxSwitch: data.ctx_switch ?? 0,
    },
    phase: (data.phase || 'IDLE') as IskraPhase,
  };

  // Cache for offline use
  safeStorage.setItem(`metrics_latest_${userId}`, JSON.stringify(result));
  return result;
}

// =============================================================================
// VOICE PREFERENCES
// =============================================================================

export async function getVoicePreferences(): Promise<VoicePreferences> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('voice_preferences')
    .select('voice_name, weight')
    .eq('user_id', userId);

  if (error || !data) return {};

  const prefs: VoicePreferences = {};
  data.forEach(row => {
    prefs[row.voice_name] = row.weight ?? 0;
  });

  return prefs;
}

export async function saveVoicePreferences(prefs: VoicePreferences): Promise<void> {
  const userId = await getUserId();

  // Upsert each preference
  for (const [voice, weight] of Object.entries(prefs)) {
    const { error } = await supabase
      .from('voice_preferences')
      .upsert({
        user_id: userId,
        voice_name: voice,
        weight: weight || 1.0,
      }, {
        onConflict: 'user_id,voice_name',
      });

    if (error) console.error('Failed to save voice preference:', error);
  }
}

// =============================================================================
// CHAT HISTORY
// =============================================================================

export async function getChatHistory(limit = 50): Promise<Message[]> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('chat_history')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: true })
    .limit(limit);

  if (error) {
    console.error('Failed to get chat history:', error);
    // Fallback to localStorage
    const cached = safeStorage.getItem(`chat_history_${userId}`);
    if (cached) {
      try {
        return JSON.parse(cached) as Message[];
      } catch {
        return [];
      }
    }
    return [];
  }

  const messages: Message[] = (data || []).map(row => ({
    role: (row.role === 'user' || row.role === 'model') ? row.role : 'user',
    text: row.text,
    deltaSignature: (row.delta_signature as string) || undefined,
  }));

  // Cache for offline use
  safeStorage.setItem(`chat_history_${userId}`, JSON.stringify(messages));
  return messages;
}

export async function addChatMessage(message: Message): Promise<void> {
  const userId = await getUserId();

  const { error } = await supabase.from('chat_history').insert({
    user_id: userId,
    role: message.role,
    text: message.text,
    voice_name: message.voice?.name,
    delta_signature: message.deltaSignature,
  });

  if (error) {
    console.error('Failed to add chat message:', error);
    // On error, append to cache as fallback
    const cached = safeStorage.getItem(`chat_history_${userId}`);
    let messages: Message[] = [];
    if (cached) {
      try {
        messages = JSON.parse(cached) as Message[];
      } catch {
        messages = [];
      }
    }
    messages.push(message);
    safeStorage.setItem(`chat_history_${userId}`, JSON.stringify(messages));
  }
}

export async function clearChatHistory(): Promise<void> {
  const userId = await getUserId();
  const { error } = await supabase.from('chat_history').delete().eq('user_id', userId);
  if (error) console.error('Failed to clear chat history:', error);
}

// =============================================================================
// MEMORY NODES
// =============================================================================

export async function getMemoryNodes(layer?: string): Promise<MemoryNode[]> {
  const userId = await getUserId();
  let query = supabase
    .from('memory_nodes')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false });

  if (layer) {
    query = query.eq('layer', layer);
  }

  const { data, error } = await query;

  if (error) {
    console.error('Failed to get memory nodes:', error);
    // Fallback to localStorage
    const cacheKey = layer ? `memory_${layer}_${userId}` : `memory_all_${userId}`;
    const cached = safeStorage.getItem(cacheKey);
    if (cached) {
      try {
        return JSON.parse(cached) as MemoryNode[];
      } catch {
        return [];
      }
    }
    return [];
  }

  const nodes: MemoryNode[] = (data || []).map(row => ({
    id: row.id,
    type: row.type as any,
    layer: row.layer as any,
    timestamp: row.created_at || new Date().toISOString(),
    title: row.title || '',
    content: row.content,
    doc_type: row.doc_type as any || undefined,
    trust_level: row.trust_level ?? undefined,
    tags: row.tags || [],
    section: row.section || undefined,
    facet: row.facet as any || undefined,
    evidence: (row.evidence as unknown as SIFTBlock[]) || [],
  }));

  // Cache for offline use
  const cacheKey = layer ? `memory_${layer}_${userId}` : `memory_all_${userId}`;
  safeStorage.setItem(cacheKey, JSON.stringify(nodes));
  return nodes;
}

export async function addMemoryNode(node: Omit<MemoryNode, 'id' | 'timestamp'>): Promise<MemoryNode> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('memory_nodes')
    .insert({
      user_id: userId,
      layer: node.layer,
      type: node.type,
      title: node.title,
      content: node.content as any,
      doc_type: node.doc_type || null,
      trust_level: node.trust_level || 1.0,
      tags: node.tags || [],
      section: node.section || null,
      facet: node.facet || null,
      evidence: node.evidence as any || [],
    })
    .select()
    .single();

  if (error) throw error;

  return {
    id: data.id,
    type: data.type as any,
    layer: data.layer as any,
    timestamp: data.created_at || new Date().toISOString(),
    title: data.title || '',
    content: data.content,
    doc_type: data.doc_type as any || undefined,
    trust_level: data.trust_level ?? 1.0,
    tags: data.tags || [],
    evidence: [],
  };
}

// =============================================================================
// AUDIT LOG
// =============================================================================

export async function logAudit(action: string, category: string, details?: Record<string, unknown>): Promise<void> {
  const userId = await getUserId();
  const { error } = await supabase.from('audit_log').insert({
    user_id: userId,
    action,
    category,
    details: details ? (details as unknown as Database['public']['Tables']['audit_log']['Insert']['details']) : null,
  });

  if (error) console.error('Failed to log audit:', error);
}

export async function getAuditLog(limit = 100): Promise<Database['public']['Tables']['audit_log']['Row'][]> {
  const userId = await getUserId();
  const { data, error } = await supabase
    .from('audit_log')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(limit);

  if (error) {
    console.error('Failed to get audit log:', error);
    return [];
  }

  return data || [];
}

// =============================================================================
// EXPORT ALL
// =============================================================================

export const supabaseService = {
  // User
  getOrCreateUser,
  updateUser,
  completeOnboarding,
  completeTutorial,
  isOnboardingComplete,
  // Tasks
  getTasks,
  saveTasks,
  addTask,
  updateTask,
  deleteTask,
  // Habits
  getHabits,
  saveHabits,
  // Journal
  getJournalEntries,
  addJournalEntry,
  // Metrics
  saveMetricsSnapshot,
  getLatestMetrics,
  // Voice
  getVoicePreferences,
  saveVoicePreferences,
  // Chat
  getChatHistory,
  addChatMessage,
  clearChatHistory,
  // Memory
  getMemoryNodes,
  addMemoryNode,
  // Audit
  logAudit,
  getAuditLog,
  // Utils
  isSupabaseAvailable,
};

export default supabaseService;
