// =============================================================================
// iskra-metrics — Deno test contract (Atom 1)
// =============================================================================
// Run in CI with: deno test --no-lock supabase/functions/_shared/iskra-metrics/
// Mirrors the existing runtime/iskraSpace/.../_shared/*_test.ts convention.
//
// These assertions encode the four PASS gates from the ADR:
//   1. Determinism  — same input → same hash → same output
//   2. Parity       — ported numbers equal fixed canonical vectors from
//                     @iskra/math (vectors frozen below; regenerated by the
//                     tsx parity harness that imports @iskra/math directly)
//   3. Missing data — absent input → unavailable/null, never a fabricated 0.5
//   4. Purity       — no throw on well-formed input; throws localized to
//                     validation, not silent placeholder substitution
// =============================================================================

import { assertEquals, assert } from 'jsr:@std/assert@1';
import { computeMetrics } from './calculator.ts';
import { ALGORITHM_VERSION } from './contracts.ts';
import { calculateShannonEntropy, interpretEntropy } from './entropy.ts';
import { calculateHFD, calculateDFA } from './fractal.ts';

// --- Fixed canonical parity vectors (from @iskra/math on these exact inputs) --
// If these ever fail, either the port drifted or @iskra/math changed and the
// algorithm_version must be bumped in lockstep.
const ENTROPY_VECTOR = {
  text: 'the fire speaks the truth the fire speaks again',
  expected: 2.197159723424149,
};
const SIGNAL_16 = [
  0.1, 0.4, 0.2, 0.8, 0.3, 0.6, 0.5, 0.9, 0.2, 0.7, 0.4, 0.85, 0.35, 0.65,
  0.55, 0.95,
];


Deno.test('algorithm version identifies the HFD formula revision', () => {
  assertEquals(ALGORITHM_VERSION, 'iskra-metrics-compute-v1.1.0');
});

Deno.test('entropy parity on frozen vector', () => {
  assertEquals(calculateShannonEntropy(ENTROPY_VECTOR.text), ENTROPY_VECTOR.expected);
});

Deno.test('entropy regime thresholds', () => {
  assertEquals(interpretEntropy(1.9), 'LOOP');
  assertEquals(interpretEntropy(3.0), 'FLOW');
  assertEquals(interpretEntropy(5.1), 'CHAOS');
});

Deno.test('fractal measures are finite on a real signal', () => {
  const hfd = calculateHFD(SIGNAL_16);
  const dfa = calculateDFA(SIGNAL_16);
  assert(Number.isFinite(hfd));
  assert(Number.isFinite(dfa));
});

Deno.test('determinism: same input → same hash and output', async () => {
  const a = await computeMetrics({ text: ENTROPY_VECTOR.text, signal: SIGNAL_16 });
  const b = await computeMetrics({ text: ENTROPY_VECTOR.text, signal: SIGNAL_16 });
  assertEquals(a.input_hash, b.input_hash);
  assertEquals(JSON.stringify(a.metrics), JSON.stringify(b.metrics));
});

Deno.test('canonical hash is key-order independent', async () => {
  const a = await computeMetrics({ text: 'x', signal: [1, 2, 3, 4, 5, 6] });
  const b = await computeMetrics({ signal: [1, 2, 3, 4, 5, 6], text: 'x' });
  assertEquals(a.input_hash, b.input_hash);
});

Deno.test('missing data → unavailable/null, never fabricated', async () => {
  const r = await computeMetrics({});
  assertEquals(r.metrics.shannon_entropy.value, null);
  assertEquals(r.metrics.shannon_entropy.unavailable, true);
  assertEquals(r.metrics.hfd.value, null);
  assertEquals(r.metrics.dfa.value, null);
  assertEquals([...r.unavailable].sort(), ['dfa', 'entropy_regime', 'hfd', 'shannon_entropy']);
});

Deno.test('short present signal → unavailable, not a 1.5/0.5 placeholder', async () => {
  const r = await computeMetrics({ signal: [1, 2, 3] });
  assertEquals(r.metrics.hfd.value, null);
  assertEquals(r.metrics.hfd.unavailable, true);
  assertEquals(r.metrics.dfa.value, null);
});
