// GENERATED by tools/generate-fractal-authority-mirrors.mjs. DO NOT EDIT.
import {
  FRACTAL_CANONICAL_SOURCE_HASH,
  FRACTAL_GENERATED_ARTIFACT_HASH,
  FRACTAL_GENERATOR_VERSION,
  FRACTAL_PARITY_CORPUS_HASH,
} from './fractal-authority-provenance.js'

export interface HfdMetricOptions {
  readonly kMax?: number
}

export interface DfaMetricOptions {
  readonly minBox?: number
  readonly maxBox?: number
}

export interface FractalMetricEvidence {
  readonly algorithm_version: string
  readonly requested_parameters: Readonly<Record<string, number>> | null
  readonly effective_parameters: Readonly<Record<string, number>> | null
  readonly sample_count: number
  readonly canonical_source_hash: string
  readonly generator_version: string
  readonly generated_artifact_hash: string
  readonly parity_corpus_hash: string
}

export interface ComputedFractalMetricResult extends FractalMetricEvidence {
  readonly status: 'computed'
  readonly value: number
}

export interface UnavailableFractalMetricResult extends FractalMetricEvidence {
  readonly status: 'unavailable'
  readonly reason: 'insufficient_samples'
  readonly required_sample_count: number
}

export interface InvalidFractalMetricResult extends FractalMetricEvidence {
  readonly status: 'invalid'
  readonly reason: 'invalid_container' | 'invalid_signal' | 'invalid_parameter'
  readonly detail: string
}

export interface NumericalFailureFractalMetricResult extends FractalMetricEvidence {
  readonly status: 'numerical_failure'
  readonly reason: 'non_finite_result'
}

export type FractalMetricResult =
  | ComputedFractalMetricResult
  | UnavailableFractalMetricResult
  | InvalidFractalMetricResult
  | NumericalFailureFractalMetricResult

export interface FractalMetricSample {
  readonly chaos: number
  readonly clarity: number
  readonly drift: number
  readonly trust: number
}

export interface ComputedFractalIndicators {
  readonly D_chaos: number
  readonly D_clarity: number
  readonly D_drift: number
  readonly H_trust: number
  readonly complexityIndex: number
  readonly edgeDistance: number
}

export interface FractalIndicatorComponents {
  readonly D_chaos: FractalMetricResult
  readonly D_clarity: FractalMetricResult
  readonly D_drift: FractalMetricResult
  readonly H_trust: FractalMetricResult
}

export type FractalIndicatorsMetricResult =
  | {
      readonly status: 'computed'
      readonly value: ComputedFractalIndicators
      readonly components: FractalIndicatorComponents
    }
  | {
      readonly status: 'unavailable' | 'invalid' | 'numerical_failure'
      readonly value: null
      readonly components: FractalIndicatorComponents
    }

export interface ValidSignal {
  readonly status: 'valid'
  readonly values: readonly number[]
}

export interface InvalidSignal {
  readonly status: 'invalid'
  readonly reason: 'invalid_container' | 'invalid_signal'
  readonly detail: string
  readonly sampleCount: number
}

export type RequestedParametersResult =
  | { readonly status: 'valid'; readonly value: Readonly<Record<string, number>> | null }
  | { readonly status: 'invalid'; readonly detail: string }

export function validateFractalSignal(value: unknown): ValidSignal | InvalidSignal {
  if (!Array.isArray(value)) {
    return {
      status: 'invalid',
      reason: 'invalid_container',
      detail: 'signal must be an array',
      sampleCount: 0,
    }
  }

  for (const item of value) {
    if (typeof item !== 'number' || !Number.isFinite(item)) {
      return {
        status: 'invalid',
        reason: 'invalid_signal',
        detail: 'signal must contain only finite numbers',
        sampleCount: value.length,
      }
    }
  }

  return { status: 'valid', values: value }
}

export function readRequestedParameters(
  value: unknown,
  allowedKeys: readonly string[],
): RequestedParametersResult {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return { status: 'invalid', detail: 'options must be an object' }
  }

  const record = value as Record<string, unknown>
  const keys = Object.keys(record)
  const unknownKey = keys.find((key) => !allowedKeys.includes(key))
  if (unknownKey !== undefined) {
    return { status: 'invalid', detail: `unsupported parameter: ${unknownKey}` }
  }

  const requested: Record<string, number> = {}
  for (const key of keys) {
    const parameter = record[key]
    if (typeof parameter !== 'number' || !Number.isFinite(parameter)) {
      return { status: 'invalid', detail: `${key} must be a finite number` }
    }
    requested[key] = parameter
  }

  return { status: 'valid', value: keys.length === 0 ? null : requested }
}

export function computedResult(
  algorithmVersion: string,
  value: number,
  sampleCount: number,
  requested: Readonly<Record<string, number>> | null,
  effective: Readonly<Record<string, number>>,
): ComputedFractalMetricResult {
  return { status: 'computed', value, ...evidence(algorithmVersion, sampleCount, requested, effective) }
}

export function unavailableResult(
  algorithmVersion: string,
  sampleCount: number,
  requiredSampleCount: number,
  requested: Readonly<Record<string, number>> | null,
): UnavailableFractalMetricResult {
  return {
    status: 'unavailable',
    reason: 'insufficient_samples',
    required_sample_count: requiredSampleCount,
    ...evidence(algorithmVersion, sampleCount, requested, null),
  }
}

export function invalidResult(
  algorithmVersion: string,
  sampleCount: number,
  requested: Readonly<Record<string, number>> | null,
  reason: InvalidFractalMetricResult['reason'],
  detail: string,
): InvalidFractalMetricResult {
  return {
    status: 'invalid',
    reason,
    detail,
    ...evidence(algorithmVersion, sampleCount, requested, null),
  }
}

export function numericalFailureResult(
  algorithmVersion: string,
  sampleCount: number,
  requested: Readonly<Record<string, number>> | null,
  effective: Readonly<Record<string, number>>,
): NumericalFailureFractalMetricResult {
  return {
    status: 'numerical_failure',
    reason: 'non_finite_result',
    ...evidence(algorithmVersion, sampleCount, requested, effective),
  }
}

function evidence(
  algorithmVersion: string,
  sampleCount: number,
  requested: Readonly<Record<string, number>> | null,
  effective: Readonly<Record<string, number>> | null,
): FractalMetricEvidence {
  return {
    algorithm_version: algorithmVersion,
    requested_parameters: requested,
    effective_parameters: effective,
    sample_count: sampleCount,
    canonical_source_hash: FRACTAL_CANONICAL_SOURCE_HASH,
    generator_version: FRACTAL_GENERATOR_VERSION,
    generated_artifact_hash: FRACTAL_GENERATED_ARTIFACT_HASH,
    parity_corpus_hash: FRACTAL_PARITY_CORPUS_HASH,
  }
}
